version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
jobs:
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 
      - run:
          name: Deploy to S3
          command: |
            pwd
            ls -a
            # aws s3 cp index.html s3://jay-static/ 
          environment:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: 'ap-south-1'

workflows:
  version: 2
  aws-cli:
    jobs:
      - deploy


