version: 2.1
# orbs:
#   aws-s3: circleci/aws-s3@1.0.6
jobs:
  deploy:
    docker:
      - image: circleci/aws-cli 
    steps:
      - checkout 
      - run:
          name: Deploy to S3
          command: |
            aws s3 cp index.html s3://jay-static/ --acl public-read
          environment:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: 'ap-south-1'

workflows:
  version: 2
  deploy-to-s3:
    jobs:
      - deploy
