version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
jobs:
  deploy:
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: "ap-south-1"
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy to S3
          command: |
            env
            ls -a
            aws s3 ls

workflows:
  version: 2
  aws-cli:
    jobs:
      - deploy
