version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
jobs:
  deploy:
    environment:
      AWS_DEFAULT_REGION: "ap-south-1"
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy to S3
          command: |
            pwd
            ls
            aws s3 sync . s3://jay-static --exclude="*" --include="index.*"
            aws cloudfront create-invalidation --distribution-id E2LJ0NCHPMZVK8 --paths "/index.html"
workflows:
  version: 2
  aws-cli:
    jobs:
      - deploy
