
version: 2.1
jobs:
  
  deploy:
    docker:
      - image: circleci/aws-cli # This image includes the AWS CLI tools
    steps:
      - checkout # Pulls the code from the repository
      - run:
          name: Deploy to S3
          command: |
            aws s3 cp ../index.html s3://jay-static 
          environment:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: 'ap-south-1'
